# Generated by Django 5.2.12 on 2026-03-14 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('hub', '0001_initial'), ('hub', '0002_assignment_integration_assignmentinstance_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=5000, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='CanvasIntegration',
            fields=[
                ('integration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hub.integration')),
                ('external_id', models.IntegerField()),
            ],
            bases=('hub.integration',),
        ),
        migrations.AddField(
            model_name='integration',
            name='assignment_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.assignmentinstance'),
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.course')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hub.coursecontent')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentCourseContentJunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.assignment')),
                ('course_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.coursecontent')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[(0, 'WINTER'), (1, 'SPRING'), (2, 'SUMMER'), (3, 'FALL')], max_length=2)),
                ('year', models.IntegerField()),
                ('section_number', models.IntegerField()),
                ('course_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.coursecontent')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstanceInstructorJunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.courseinstance')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
