# Generated by Django 5.2.12 on 2026-03-15 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_squashed_0002_assignment_integration_assignmentinstance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hub.coursecontent'),
        ),
    ]
