# Generated by Django 5.2.12 on 2026-03-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_alter_coursecontent_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstance',
            name='semester',
            field=models.IntegerField(choices=[(0, 'WINTER'), (1, 'SPRING'), (2, 'SUMMER'), (3, 'FALL')]),
        ),
    ]
