# Generated by Django 5.2.12 on 2026-03-15 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_alter_courseinstance_semester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinstanceinstructorjunction',
            name='course_instance',
        ),
        migrations.RemoveField(
            model_name='courseinstanceinstructorjunction',
            name='instructor',
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='assignments',
            field=models.ManyToManyField(to='hub.assignment'),
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='instructors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AssignmentCourseContentJunction',
        ),
        migrations.DeleteModel(
            name='CourseInstanceInstructorJunction',
        ),
    ]
