# Generated by Django 5.2.12 on 2026-03-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_remove_courseinstanceinstructorjunction_course_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='overview',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='syllabus',
            field=models.CharField(max_length=50000, null=True),
        ),
    ]
