# Generated by Django 5.2.12 on 2026-03-17 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_coursecontent_overview_coursecontent_syllabus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration',
            name='assignment_instance',
        ),
        migrations.AddField(
            model_name='integration',
            name='assignment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hub.assignment'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AssignmentInstance',
        ),
    ]
