# Generated by Django 5.2.12 on 2026-03-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_remove_integration_assignment_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
