# Generated by Django 5.2.12 on 2026-04-05 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_assignment_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.assignment')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.courseinstance')),
            ],
        ),
        migrations.CreateModel(
            name='CourseIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.courseinstance')),
            ],
        ),
        migrations.RemoveField(
            model_name='integration',
            name='assignment',
        ),
        migrations.CreateModel(
            name='CanvasAssignmentIntegration',
            fields=[
                ('assignmentintegration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hub.assignmentintegration')),
                ('external_id', models.IntegerField()),
            ],
            bases=('hub.assignmentintegration',),
        ),
        migrations.CreateModel(
            name='CanvasCourseIntegration',
            fields=[
                ('courseintegration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hub.courseintegration')),
                ('external_id', models.IntegerField()),
            ],
            bases=('hub.courseintegration',),
        ),
        migrations.DeleteModel(
            name='CanvasIntegration',
        ),
        migrations.DeleteModel(
            name='Integration',
        ),
    ]
