# Generated by Django 5.2.12 on 2026-04-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_assignmentintegration_courseintegration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='title',
            field=models.CharField(default='Typical 149', max_length=200),
            preserve_default=False,
        ),
    ]
